# Generated by Django 2.2.20 on 2021-09-26 10:58

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        owners_phonenumber = flat.owners_phonenumber
        pure_phonenumber = phonenumbers.parse(owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                pure_phonenumber, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20210926_1352'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers),
    ]
