# Generated by Django 2.2.20 on 2021-09-26 14:07

from django.db import migrations


def copy_info_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        if flat.owner_pure_phone:
            Owner.objects.get_or_create(
                name=flat.owner,
                phonenumber=flat.owners_phonenumber,
                pure_phone=flat.owner_pure_phone
            )
        else:
            Owner.objects.get_or_create(
                name=flat.owner,
                phonenumber=flat.owners_phonenumber,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(copy_info_to_owner)
    ]
