# Generated by Django 2.2.20 on 2021-09-26 17:57

from django.db import migrations


def add_flats_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    owners = Owner.objects.all()
    for owner in owners:
        owner_flats = [flat for flat in Flat.objects.filter(owner=owner.name)]
        owner.flats.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210926_2056'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owners)
    ]
